@startuml
!$bgColor = '#12263A'
!$primaryColor = '#FCFFFD'
!$secondaryColor = '#06BCC1'
skinparam linetype ortho
skinparam backgroundColor transparent
skinparam class {
  BackgroundColor $bgColor
  FontColor $primaryColor
  BorderColor $secondaryColor
  AttributeFontColor $primaryColor
}
hide circle
@enduml
